---
title: "Windows Setup Checklist"
author: "[github.com/blairw](https://github.com/blairw/)"
format:
  html:
    code-copy: true
    embed-resources: true
    include-in-header:
    - text: |
       <link rel = "shortcut icon" href = "resources/windows.png" />
    toc: true
    theme:
      - default
    
---

## OOBE (Out of Box Experience) Initial Setup

### Setup with offline account

In **Windows 11**, this is now almost unreasonably difficult but there is still a way around it:

1. During the OOBE ("Out of Box Experience") initial setup, **disconnect all network cables and do not connect to WiFi.** ⚠️
2. Even though OOBE looks like a fullscreen guided app, you can actually open up a command prompt using <kbd>SHIFT</kbd> + <kbd>F10</kbd>
3. At the command prompt, enter: `OOBE\BYPASSNRO` (yes, without any spaces; yes, with a backslash)
    - This will trigger a reboot, this is expected behaviour.
4. In the now-rebooted OOBE, again, do not connect any network cables and do not connect to WiFi.
    - Use <kbd>SHIFT</kbd> + <kbd>F10</kbd> again to pull up a command prompt again
    - This time: `ipconfig /release`
5. Now, during this OOBE second run, you will be allowed to click **I don't have Internet** when prompted to connect to the Internet
    - Then you can click **Continue with limited setup** and you will be allowed to create an offline account. 👍

Adapted from: [https://www.tomshardware.com/how-to/install-windows-11-without-microsoft-account](https://www.tomshardware.com/how-to/install-windows-11-without-microsoft-account)

### After OOBE

- [ ] Connect to the Internet and activate Windows
- [ ] Enable BitLocker and print the key to PDF

Then proceed to next section (Security).



## Security

### Basics

- [ ] Turn off autoplay/autorun
- [ ] Run `taskmgr` and disable unwanted startup applications

### Block AAD/Workplace Join

- [ ] Use `regedit` to access:

    ```cmd
    Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WorkplaceJoin
    ```

- [ ] Set DWORD `BlockAADWorkplaceJoin` = 1.

### Sensible Start Menu

- [ ] Disable all "Cloud content search"
    - Go to start menu, type **Cloud Search settings**, then open up that relevant part of the Settings app
    - Turn OFF everything under **"Cloud content search"**
- [ ] Use `regedit` to modify:
    - `HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows`
        - Add `Explorer`, and in it, add:
            - `DisableSearchBoxSuggestions` DWORD (32-bit) = 1
            - `HideRecentlyAddedApps` DWORD (32-bit) = 1

See also:

- https://pureinfotech.com/disable-web-search-windows-10-version-1803/
- https://www.thewindowsclub.com/show-or-hide-recommended-list-in-start-menu-on-windows-11




## Performance

### Windows Settings

- **System** &rarr; Display &rarr; Brightness & color (heading) &rarr; Brightness. Open this part of the accordion.
  - Switch OFF _"Change brightness automatically when lighting changes"_.
  - Switch OFF _"Change brightness based on content"_ (defaults to "On Battery Only", we want it OFF completely). 

### Old Alt+Tab

Adapted from https://winaero.com/enable-classic-alttab-dialog-in-windows-11/

```cmd
Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer
```

Set DWORD `AltTabSettings` = 1.

**This will require a reboot.**



## Software Setup

### Initial setup of Scoop first

Use Powershell:

https://scoop.sh/

Then:

```powershell
scoop install 7zip git fastfetch

# Python 3.11
scoop bucket add versions
scoop install versions/python311

# Quarto
scoop bucket add extras
scoop install extras/quarto
```

### Using Python in Powershell

```powershell
python -m venv .venv
.\.venv\Scripts\Activate.ps1

# Equivalent of `which python`
(Get-Command python).Path

# If you need to delete a folder, this is the equivalent of `rm -rf`
rm some_folder -Recurse -Force
```


### Initial setup of Chocolatey

In an admin `cmd`, run:

```cmd
@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
```

(Source: https://docs.chocolatey.org/en-us/choco/setup)



### Google Chrome

- [ ] Check [https://community.chocolatey.org/packages/googlechrome](https://community.chocolatey.org/packages/googlechrome) to make sure all relevant tests are passing.
- [ ] In an admin `cmd`, run:
    ```
    choco install -y googlechrome
    ```


### Install software using Chocolatey.

For each of the following, first check the package status at:

```sql
https://community.chocolatey.org/packages/PLEASE_PUT_PACKAGE_NAME_HERE
```

If all relevant tests are passing, then you can run the `choco install` command. If there are relevant tests that are not passing, consider installing manually.

In other words, do these **one at a time**.


```cmd
# Get these started first.
choco install -y sudo
choco install -y chocolateygui
choco install -y dropbox
choco install -y nextcloud-client

# Should be OK, but please check, the status might have changed by the time you're reading this.
choco install -y audacity
choco install -y audacity-ffmpeg
choco install -y audacity-lame
choco install -y brave
choco install -y cryptomator
choco install -y everything
choco install -y firefox
choco install -y irfanview
choco install -y irfanviewplugins
choco install -y libreoffice-still
choco install -y logioptionsplus
choco install -y mp3tag
choco install -y monitorian
choco install -y nettraffic
choco install -y notepadplusplus.install
choco install -y paint.net
choco install -y passwordsafe
choco install -y powertoys
choco install -y signal
choco install -y sumatrapdf.install
choco install -y thunderbird
choco install -y vlc.install
choco install -y vscodium.install
choco install -y zoom

# Optional, you may not need them
choco install -y greenshot
choco install -y logitech-options
choco install -y mactype
choco install -y slack

# VirtualBox - first check https://www.virtualbox.org/wiki/Downloads for any notices about the most recent release - sometimes the most recent release causes BSOD
choco install -y virtualbox

# Potentially problematic, but please check, they might be OK by the time you're reading this.
choco install -y atom.install
choco install -y librewolf
choco install -y processhacker.install

# Syncthing - if the status on Chocolatey is problematic, use https://github.com/Bill-Stewart/SyncthingWindowsSetup/releases/
# As advised by https://syncthing.net/downloads/
choco install -y syncthing

# TBC
choco install -y filezilla
choco install -y zotero
```

whatsapp???

cinst -y  ant-renamer
cinst -y  git-fork
cinst -y handbrake.install hwinfo
cinst -y   qttabbar  tabby 

Only if you want battery bar:

    cinst -y batterybar

Only if you want xampp:

    cinst -y xampp-81

Only if you want nordvpn:

    cinst -y nordvpn

Only if you want docker:

    cinst -y docker-desktop

DO NOT install the following programs using Chocolatey:

-   Spotify
-   WhatsApp

### CSVed

Install manually

### Window-switcher

Install manaully: https://github.com/sigoden/window-switcher


### Explorer++

Use https://github.com/derceg/explorerplusplus

Latest beta supports hidpi scaling.

### Microsoft Office

-   Manually install from office.com

### Three Finger Drag

- https://github.com/ClementGre/ThreeFingerDragOnWindows/
- If it complains that you dont have .NET Desktop Runtime 6, get it from https://community.chocolatey.org/packages/dotnet-6.0-desktopruntime


## WSL/Ubuntu


Follow instructions at https://docs.microsoft.com/en-us/windows/wsl/install - be careful not to install using other legacy methods.

- Note that Ubuntu will be automatically installed so **you do NOT need to download Ubuntu from the App Store**
- wsl -l -v  # check current version


### Ubuntu handy installs

```zsh
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install bat btop dos2unix ffmpeg libreoffice lolcat neofetch pandoc python3-venv rclone
```

### Git config

Note: For GitHub, you'll need to generate a Personal Access Token (PAT) at https://github.com/settings/tokens

    git config --global credential.helper store
    git config --global user.name "YOUR_NAME_GOES_HERE"
    git config --global user.email "EMAIL_ADDRESS_GOES_HERE"

### pbcopy equivalent

Is just `clip.exe`. :)

Please note, if you want to be able to copy characters that non-ascii Unicode (e.g., mdash), you will need to go to: System settings &rarr; Time & language &rarr; Language & region &rarr; Administrative language settings &rarr; Language for non-Unicode programs &rarr; **Change system locale...** And then enable **Beta: Use Unicode UTF-8 for worldwide language support**.

Source: https://github.com/microsoft/WSL/issues/11047#issuecomment-1946510386


### Cron

Make sure your user account is actually added to the `crontab` group otherwise nothing will happen:

    sudo usermod -a -G crontab blair

Check cron status (`start` and `stop` only if needed):

    sudo service cron status
    sudo service cron start
    sudo service cron stop


&nbsp;
&nbsp;
&nbsp;

Favicon by [Yusuke Kamiyamane](https://p.yusukekamiyamane.com/). Licensed under a Creative Commons Attribution 3.0 License.


## Device-Specific Instructions

### If needed: block Windows 10 Update to Windows 11

Use the `TargetReleaseVersionInfo` method documented at https://www.askwoody.com/forums/topic/further-evidence-of-forced-upgrade-to-win10-version-2004-possibly-due-to-a-pause-updates-bug/#post-2275152

The following commands in `sudo cmd`

    reg add HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate /f /v TargetReleaseVersion /t REG_DWORD /d 1
    reg add HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate /f /v TargetReleaseVersionInfo /t REG_SZ /d 22H2

Be sure to check latest release version (e.g., `22H2`) as per https://en.wikipedia.org/wiki/Windows_10

